### ISSUE TITLE
Could not find file 'clammicrobench_nasm_rob.asm'.

### ISSUE THREAD

**Issue by edisonchan** [clamchowder/Microbenchmarks#7]
```
PS G:\git\Microbenchmarks\AsmGen\bin\Release\net7.0-windows> ./AsmGen.exe autocopy
Automatically copying files, based on default VS paths
Moved clammicrobench_nasm_zen3rob.asm
Moved clammicrobench_nasm_rob.asm
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'G:\git\Microbenchmarks\AsmGen\bin\Release\net7.0-windows\clammicrobench_nasm_rob.asm'.
File name: 'G:\git\Microbenchmarks\AsmGen\bin\Release\net7.0-windows\clammicrobench_nasm_rob.asm'
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at AsmGen.Program.CopyFiles(String targetDir, String[] fileNames) in G:\git\Microbenchmarks\AsmGen\Program.cs:line 212
   at AsmGen.Program.Main(String[] args) in G:\git\Microbenchmarks\AsmGen\Program.cs:line 196
```

Build with latest clone and just changed the target framework to 6.0 or 7.0(because 5.0 would cause 'Metrics' does not exist in the namespace 'System.Diagnostics' error).

**Comment by clamchowder** [comment]
VS/NASM not used anymore for structure size tests
